[database]
host = '127.0.0.1'
port = '3306'
user = 'root'
password = '123456'
database = 'zy_blog'

[general]
domain = 'http://127.0.0.1:5000/'
title = '七棵树'
theme = 'default'
api_host = 'https://u.lho.cc/'
#支持彩虹聚合登录的api
app_id = '9999'
app_key = '123123'

[admin]
key = '237'

