[database]
host = '127.0.0.1'
port = '3306'
user = 'root'
password = '123456'
database = 'zb'

[general]
version = '1.2.104'
domain = 'http://7trees.cn/'
title = '7trees'
beian = '京ICP备999999'
theme = 'cn.7trees.2024'
#支持彩虹聚合登录的api
api_host = 'https://u.cccyun.cc/'
app_id = '2764'
app_key = '64f4f4d13211e2d9be472b03cdc7d46a'

[notification]
host = 'http://127.0.0.1:9422'
port = '9422'

[mail]
host = 'smtp.163.com'
port = '465'
user = 'support@7trees.cn'
password = 'your_mail_pass'


[admin]
key = '237'

